default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: rails_portfolio_development

test:
  <<: *default
  database: rails_portfolio_test

production:
  <<: *default
  database: rails_portfolio_production
  username: rails_portfolio
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
