# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252377a67624451b79a27445d5abb373793d525749efefd18216d80c17c1fe31b20b8c0d760eb5302d7543725774431cf8ab5cc41e66dcf06e26c1ffd8f3d367

test:
  secret_key_base: 5d0429ae55eecca222aee8752d2190981968ea5e6b5eb94c4c5656a7c9b4f6befeadd10b268185dd64780721ded08d4214668940b5f9e858e9be9633dbab43a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
